Exygy/askdarcel-web

- webpack.config.js
**Description**
Currently, one has to have a .yml file containing environment variables for the build to work. This makes that optional, which I think is good since the build already supports falling back on local environment variables. 
**Tasks**
- wrap environment configuration read in else statement
- initialize config object so it's not undefined if a configuration file doesn't exist
> make configuration yml file optional

- README.md
- app/styles/main.scss
- app/styles/utils/_borders.scss
- app/styles/utils/_colors.scss
- app/styles/utils/_helpers.scss
- app/styles/utils/_layoututils.scss
- app/styles/utils/_reset.scss
- app/styles/utils/_spacing.scss
This PR addresses [issue ticket](https://www.notion.so/exygy/Build-out-styling-system-cb2ec2a0f19641a6b5d26013983e2b55?pvs=4)
The motivation behind this is try to get the team on a good footing re: global styles + theme. There was a lot to consider when this was done: trying to merge the design system used for our415 designs with AskDarcelWeb, a long term strategy for a merge with the origin repo, building something fast enough for the MVP, etc. What I settled on was trying to accomplish two goals:
1. build utils and tokens for the remaining work for the MVP
2. leverage the current theming tools AskDarcel to be in line with the utils and tokens built for our415 so the spacing, typography, color palette etc in the askdarcel web components looks inline with the our415 site. There's still …
> add tokens, util classes for our415; modify theme

- .vscode/settings.json
- app/Router.tsx
- app/components/layouts/BackNavigation.tsx
- app/components/layouts/SecondaryNavigation.module.scss
- app/components/layouts/SecondaryNavigationLayout.tsx
See Notion: https://www.notion.so/exygy/Back-Navigation-Bar-2564a5fd669e46f79eeba5ec61ff3c47
Demo with entry from incognito and then referring page:
https://github.com/Exygy/askdarcel-web/assets/5185/a9bfda17-0fae-4201-b8b0-c3408406d5b2
Run the app locally and visit http://localhost:8080/organizations/60
<details>
<summary>Reviewer Notes:</summary>
- Either explicitly ask a clarifying question, request changes, or approve the PR …
> Adds `SecondaryNavigationLayout` and `BackNavigation` component

- app/components/listing/ServiceDetails.tsx
- app/components/search/SearchResults/SearchResults.module.scss
- app/components/search/SearchResults/SearchResults.tsx
- app/pages/ServiceListingPage/ServiceListingPage.tsx
- app/styles/utils/_helpers.scss
- app/utils/strings.spec.ts
- app/utils/strings.ts
This adds some changes missed by https://github.com/Exygy/askdarcel-web/pull/48, and a fix and a test for removeAsterisksAndHashes(). 
- removeAsterisksAndHashes() fix - add * to function (was only removing # )
- removeAsterisksAndHashes() test - takes in string with * and # and returns a string with out (this strips unwanted headers that cause a11y problems)
- formats the long-descriptions in the service listing page components
> Long description fixes

- app/App.tsx
- app/components/ui/Navigation.tsx
- app/components/ui/SiteSearch.module.scss
- app/components/ui/SiteSearch.tsx
This is part of N to implement the new site navigation. These changes add some needed separation and refinement of the header components. Just moving code around and setting up placeholders for new components.
Additionally:
Screenshot:
> [OUR415-87] Decouples `<SiteSearch />` from `<Navigation />`

- app/components/ui/Footer/Footer.tsx
- app/components/ui/Footer/FooterColumn.tsx
- app/components/ui/Footer/FooterLink.tsx
- app/hooks/StrapiAPI.ts
- app/models/Strapi.ts
The idea here is to create a stronger boundary between the api adapter layer and the domain object data consumed by components. It's a little bit more overhead at the start, but IME this creates a valuable clarity for devs to know when they are working with transformed or raw data objects. 
Additionally:
> Separates api response types from model types

- app/components/search/Sidebar/MapToggleButtons.tsx
- app/components/ui/Cards/CategoryCard.module.scss
- app/components/ui/MapElements.tsx
Quick PR per https://www.notion.so/exygy/Text-Center-Aligned-Instead-of-Left-Aligned-on-Mobile-in-Browse-Service-fb693e28b92b4d90afa514201cd6fa3b
Makes it so the category cards in the Browse Services section are left aligned on mobile
> Mobile category cards are left aligned

- app/components/search/SearchMap/SearchEntry.tsx
- app/components/search/SearchMap/SearchMap.tsx
- app/components/search/SearchResults/SearchResult.tsx
- app/models/SearchHits.ts
My [previous solution](https://github.com/Exygy/askdarcel-web/pull/98) was incomplete as I forgot to move the marker label computation logic into the new transform. Map marker labels were rendering out either duplicate or incorrectly indexed because I wasn't actually using addresses to create the label. 
Before: 
After:
> [OUR415-195] Fixes incorrect marker location labels

- app/components/search/Header/Header.tsx
- app/components/search/Header/SearchHeaderSection.module.scss
- app/components/search/Header/SearchHeaderSection.tsx
- app/components/search/SearchMap/SearchMap.tsx
- app/components/search/SearchResults/SearchResults.tsx
- app/pages/HomePage/HomePage.tsx
- app/styles/st-base/_layout.scss
Closes `Add hidden sr-only headers to sections for a11y (i.e. search results, pagination)` todo of https://www.notion.so/exygy/a11y-bugs-cf30e04daa794b04879af76207b9b96a
This PR adds visually hidden headers around the site where they are missing to improve user a11y:
- h1 on homepage
- h1 on search results page (remove old h1)
- add h2s on search results page to let user know what each section is for
> Add screen-reader only headers to site where missing (a11y)

- app/components/ui/Navigation/NavigationFocusReset.tsx
This PR adds a quick fix to NavigationFocusReset so that it only resets user focus when they switch top-level pages and NOT when they use the eligibility filters or search something new from a /search page. This improves UX and a11y so that the user does not have to tab nav from the top of the page when they select a checkbox or radio button.
> Focus State Update

- app/components/ui/Cards/OppEventCard.module.scss
- app/components/ui/Cards/OppEventCard.tsx
- app/components/ui/inline/Button/Button.tsx
Closes `[Homepage] Cards in “Open opportunities” and “Upcoming events” sections are inaccessible. Screen reader only reads “View more”. Potentially solved with descriptive aria-label (in progress)` of the [a11y bugs multi-ticket](https://www.notion.so/exygy/a11y-bugs-cf30e04daa794b04879af76207b9b96a)
- Adds isVisualOnly class to Button so it can maintain styling but not cause a11y confusion
- Adds correct link to card (still need to build out event and opportunity pages but they will be at those routes)
- Adds hover state to card
> OppEventCard a11y improvements

- app/components/search/Header/Header.tsx
- app/components/search/SearchResults/SearchResult.tsx
- app/components/ui/BackButton.tsx
- app/components/ui/Footer/Footer.tsx
- app/components/ui/Navigation/Navigation.tsx
- app/styles/st-base/_layout.scss
This PR closes the following todos:
- [Search Page] Print view on (/search) should include phone number and website rather than icons
- [Search Page] “Print All Results” only prints current page (I don’t know if we can fix this) Maybe we should change the copy to Print this page.
- [Sitewide] Hide header and footer from print view using “.no-print” class
from Visual bugs muliticket https://www.notion.so/exygy/Visual-bugs-c3450de5b2944517b933df773dd1deef
IMO these aren't a huge deal but since we are including a print button on the site, the print page should provide value (i.e. include phone numbers and URLs that are visually hidden on site) and hide components that don't provide value (i.e. footer)
> Print view ux edits

- app/components/ui/Navigation/DesktopNavigation.module.scss
- app/components/ui/Navigation/DropdownMenu.module.scss
- app/components/ui/inline/Button/Button.module.scss
Fixes `Fix tiny icons` bug in https://www.notion.so/exygy/Visual-bugs-c3450de5b2944517b933df773dd1deef
Two separate issues that seemed like a more systemic problem but are not. Button icons and dropdown chevron were both too small and this PR restores their former correct sizes.
> Icon size bug

- app/components/search/Header/CustomDropdown.module.scss
- app/components/search/Sidebar/Sidebar.module.scss
- app/components/search/Sidebar/Sidebar.tsx
- app/components/ui/Navigation/DesktopNavigation.module.scss
- app/components/ui/Navigation/DropdownMenu.module.scss
- app/components/ui/Navigation/MobileNavigation.module.scss
- app/components/ui/Navigation/SkipButton.module.scss
- app/hooks/MenuHooks.ts
- app/styles/utils/_layoututils.scss
This PR addresses `[Search Page] Filters sidebar should close on click away (/search)` todo of visual bugs multi ticket https://www.notion.so/exygy/Visual-bugs-c3450de5b2944517b933df773dd1deef
It also adds a z-index back in that was causing visual errors with the sidebar being hidden by map.
> Close eligibilities sidebar on click away

- app/components/listing/ListingPageWrapper.module.scss
- app/components/search/Header/Header.module.scss
- app/components/search/Header/SearchHeaderSection.module.scss
- app/components/search/SearchResults/SearchResults.module.scss
- app/components/search/Sidebar/Sidebar.module.scss
- app/components/ui/Accordions/Accordion.module.scss
- app/components/ui/Hero/Hero.tsx
- app/components/ui/Masthead/Masthead.module.scss
- app/pages/ServiceListingPage/ServiceListingPage.module.scss
- app/styles/st-base/_layout.scss
- app/styles/utils/_helpers.scss
This PR closes the following items of https://www.notion.so/exygy/Responsiveness-bugs-49256bf5cc954630be508a01b54eb457:
- [Search] On search listings cards, list items font is smaller than rest of text
- [Search] Search icon is white on mobile but should be black
- [Service] Individual service page: link in subhead smaller than rest of text
- [FAQs] Accordion headers are centered on mobile but should not be
as well as some visual bugs I noticed in the process:
- Google translate select dropdown was blue on mobile but should be black
- Search results cards tablet size visual bugs
- Hero buttons on homepage were too big
- There were some spacing discrepancies on mobile /search
- DropdownMenu on /search page text did align with rest of content (due to padding)
- Sticky filters header was …
> Mobile QA multi

- app/components/search/SearchMap/SearchMap.scss
- app/components/search/SearchResults/SearchResults.module.scss
🎟️ : [notion.so/exygy/Zoom-level-cuts-off-some-results-33c6ba214bb44c34b67edf9443e1c75c?pvs=4](https://www.notion.so/exygy/Zoom-level-cuts-off-some-results-33c6ba214bb44c34b67edf9443e1c75c?pvs=4)
Before:
https://github.com/user-attachments/assets/7610b4e9-f561-4646-ad68-6e58beee6500
After: 
https://github.com/user-attachments/assets/b59ed537-d7e7-4296-84c7-03f617d438c5
> [OUR415-193] Converts search results from grid to flex with min width for result list

- docker/templates/default.conf.template
- webpack.config.js
Reverts Exygy/askdarcel-web#200
Oops, learned the hard way that heroku does not support brotli compression in their nginx build pack yet. See: https://github.com/heroku/heroku-buildpack-nginx/issues/109
From logs: 
```
2024-09-16T18:18:34.926620+00:00 app[web.1]: nginx: [warn] the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /etc/nginx/nginx.conf:2
2024-09-16T18:18:34.926889+00:00 app[web.1]: 2024/09/16 18:18:34 [emerg] 2#2: unknown directive "brotli" in /etc/nginx/conf.d/default.conf:38
2024-09-16T18:18:34.926889+00:00 app[web.1]: nginx: [emerg] unknown directive "brotli" in /etc/nginx/conf.d/default.conf:38
2024-09-16T18:18:34.963929+00:00 heroku[web.1]: Process exited with status 1
2024-09-16T18:18:34.988087+00:00 heroku[web.1]: …
```
> Revert "Adds brotli compression with gzip fallback"

- app/components/ui/Navigation/Navigation.tsx
- app/pages/ServiceListingPage/ServiceListingPage.tsx
🎟️  [As a person searching for  Services, when I click on search result and the data is not available in the Shelter Tech API, I should see a partial detail view with a call to action](https://www.notion.so/exygy/As-a-person-searching-for-Services-when-I-click-on-search-result-and-the-data-is-not-available-in--1133433f03d080dd9dccdb09b0cc4a18?pvs=4)
- http://localhost:8080/services/999
- http://localhost:8080/services/4269
- http://localhost:8080/services/bad_bad_bad
- For example, if they change the structure of the JSON in their API responses.
> [OUR415-300] Adds fallback to fetch a Service directly from Algolia if missing from the Shelter Tech API

- app/pages/constants.ts
🎫 : [Change “Children’s Care” to “Childcare”](https://www.notion.so/exygy/Change-Children-s-Care-to-Childcare-1163433f03d08027be50f9c7445511b5?pvs=4)
This PR closes OUR415-303:
- Edits "Children's Care" language to "Childcare"
- Updates the categoryId to use Childcare category instead of Children's Care
- Updates the slug of the category page to be `/childcare/results`
- Edits the Strapi Header dropdown name and slug values
> Change Children's Care to Childcare category

- app/components/EmailSignup/EmailSignup.module.scss
- app/components/EmailSignup/Emailsignup.tsx
- app/components/ui/inline/Button/Button.tsx
🎟️: [Build a sign up form](https://www.notion.so/exygy/Build-a-sign-up-form-c55f98f2603c44cb82d55bd7538fecad?pvs=24)
This PR:
- Updates `EmailSignup` component
- Updates button to take in `IsExternalLink` boolean prop (before the href value determined if the link was external (open in new tab) or internal (same tab), however in this situation, the Button is opening a link in the popup window not in a new tab)
> Newsletter signup section

- app/components/search/SearchMap/SearchMap.tsx
- app/components/search/SearchResults/SearchResults.tsx
🎟️ [Search this Area button doesn’t reset the page number](https://www.notion.so/exygy/Search-this-Area-button-doesn-t-reset-the-page-number-1043433f03d080579759dfd9bfefebd3?pvs=4)
Fixes the resetting issue but adds a little more ceremony to lift the interaction handling for the `Search this Area` button up a component level to the `SearchResults` component. This has the benefit of decoupling the `SearchMap` component from other components and app state by letting it simply focus on emitting actions.
After:
https://github.com/user-attachments/assets/02361a41-96cf-4948-baae-fbb2d952639b
> [OUR415-287] Fixes pagination reset upon user interactions with map

- app/components/ui/Footer/FooterLink.tsx
This, along with content changes in Strapi, resolve [Footer bug](https://www.notion.so/exygy/Footer-bug-1063433f03d080e89301d888dc2c15fe?pvs=24)
> Edit footer link label to use strapi text instead of url

- app/pages/ServiceDetailPage/ServiceDetailPage.tsx
Quick improvement I found while looking at [Some service listings fail to open detail pages, displaying API response errors.](https://www.notion.so/exygy/Some-service-listings-fail-to-open-detail-pages-displaying-API-response-errors-1063433f03d080c79e57d29ba6c242d7?pvs=24)
NOTE: That ticket seems to be handled already but the browser tab title was still "error" so I fixed that here
> quick title improvement for service detail page

- app/Router.tsx
- app/components/ui/PageNotFound.module.scss
- app/components/ui/PageNotFound.tsx
- app/pages/OrganizationDetailPage.tsx
- app/pages/PageNotFoundPage/PageNotFoundPage.module.scss
- app/pages/PageNotFoundPage/PageNotFoundPage.tsx
- app/pages/ServiceDetailPage/ServiceDetailPage.tsx
🎫: [404 page / page not found](https://www.notion.so/exygy/404-page-page-not-found-13e3433f03d08026b9f2ca1899cb687c?pvs=24)
This creates the `PageNotFound` component and page per mockup
Adds component to:
- `ServiceDetailPage`
- `OrganizationDetailPage`
NOTE: This keeps the back page and also makes it easy to pass in different messages as props if we decide to do so in the future
Adds `PageNotFoundPage` to `Router` as a catch-all 
**Firefox 132.0.2 (aarch64)**
> [Our415-45] Page Not Found page and component 

- app/components/ui/Navigation/MobileNavigation.module.scss
- app/styles/utils/_layoututils.scss
🎫: [Mobile menu cut off](https://www.notion.so/exygy/Mobile-menu-cut-off-1443433f03d0800c88e6dfc1d11716ba?pvs=4)
This PR styles the mobile menu on mobile sized screens so that it is 100vw wide.
Before:
After:
> Mobile menu cutoff bug fix 

- app/components/ui/Navigation/MobileNavigation.tsx
- app/components/ui/Navigation/Navigation.module.scss
- app/components/ui/Navigation/Navigation.tsx
- app/components/ui/Navigation/TopBanner.module.scss
- app/components/ui/Navigation/TopBanner.tsx
🎫: [Explore moving language selector out of mobile menu](https://www.notion.so/exygy/Explore-moving-language-selector-out-of-mobile-menu-1443433f03d080c88680cc4485e4357d?pvs=24)
This PR: 
- Moves the Google Translate widget out of the desktop navbar and the mobile dropdown and into its own TopBanner component, used for both desktop and mobile
- Navbar is meant to be sticky, while TopBanner is not, so as user scrolls the banner disappears leaving them with more screen real estate to see actionable content
NOTE: This is not meant to be a final iteration but something we can test on both mobile and desktop on the staging URL that design can then QA / request changes.
> [Our415-93] Move google translate into TopBar and hide elsewhere

- app/App.test.tsx
- app/App.tsx
- app/pages/BrowseResultsPage/BrowseResultsPage.tsx
- app/pages/EventDetailPage/EventDetailPage.test.tsx
- app/utils/useAppContext.tsx
- jest.config.ts
- pull_request_template.md
- test/templates/Template.test.tsx
This was likely broken since the big React 18 refactor. The root cause is that the user's map location -- the somewhat poorly named `aroudnLatLng` -- is never set on site/page load. It was only getting set when the user clicked the `Search this area` button on the map. This meant the distance filtering seemed to work sporadically from the user's point of view, but in most cases it simply didn't. 
- [🐞 Report](https://www.notion.so/exygy/Verify-that-Distance-filter-works-17e3433f03d0803aba26c8574d1683a8?pvs=4)
- Adds a test file for the root `<App />` component
- Asserts basic render
- Asserts correct props are created and passed to `<AppProvider />`, including the related location props to fix this bug
https://github.com/user-attachments/assets/f29054d2-1aa0-4bd5-8319-054d588252b1
- This …
> [OUR415-BUG-29] Fixes `Distance` filter by setting `aroundLatLng` (user's map location) on site load

- app/components/ui/Navigation/MobileNavigation.module.scss
🤷 Guess we missed it!
- [🎫 Task](https://www.notion.so/exygy/Mobile-menu-overlay-placement-1113433f03d080efa1f1c294e5c56646?pvs=4)
| mobile  |  ![image](https://github.com/user-attachments/assets/a1806fed-4597-4b83-8304-9676e6285a88)       |   ![image](https://github.com/user-attachments/assets/7d859f5a-bce6-49d3-9c99-f31ea603463e) |
> [OUR415-BUG-22] Ensures category navigation dropdown on mobile is flush right 

- app/components/ui/Cards/EventCard.module.scss
- app/components/ui/TwoColumnContentSection/SingleColumnContentSection.module.scss
- app/pages/constants.ts
- app/utils/formatEventDate.test.ts
- app/utils/formatEventDate.ts
- app/utils/formatEventTime.test.ts
- Fixes homepage event card width (not sure why this regressed for the flex row layout)
- Switches the top level category for childcare for debugging https://www.notion.so/Why-is-Childcare-top-level-category-pulling-in-eligibilities-into-sidebar-17e3433f03d08087b45cf3c8225a8679?pvs=4
- Fixes date bug that _only_ was showing up in Safari. Chrome/Firefox very forgiving of strange date formats like `2025/01-29`
> [OUR415-BUG-43] and a few other minor fixes

- Dockerfile
This updates the Dockerfile so it can build an image. It would previously fail because it expected `npm run build` to already have run.
> fixes dockerfile so it builds properly

- app/components/ui/BackButton.tsx
[Need to click “Back to Services” button twice on service page for it to work properly](https://www.notion.so/exygy/Need-to-click-Back-to-Services-button-twice-on-service-page-for-it-to-work-properly-1823433f03d08005a903cabaf65dde6e?pvs=4)
I submitted this bug but i can no longer repro. Did change the mobile width to not be full width for better UX / design
> Back button mobile width

- app/components/DetailPage/DetailPageWrapper.tsx
- app/pages/BrowseResultsPage/BrowseResultsPage.tsx
- app/pages/EventDetailPage/EventDetailPage.tsx
- app/pages/OrganizationDetailPage.tsx
- app/pages/SearchResultsPage/SearchResultsPage.tsx
- app/pages/ServiceDetailPage/ServiceDetailPage.tsx
🎫: [When user is scrolled down on page and clicks an internal link, they are still scrolled down on page](https://www.notion.so/exygy/When-user-is-scrolled-down-on-page-and-clicks-an-internal-link-they-are-still-scrolled-down-on-page-1823433f03d080b8b15ce3fc9060ccd5?pvs=4)
This PR:
- adds scrollTo logic on the DetailPageWrapper (and removes it from pages that use this wrapper)
- adds scrollTo logic on browse and search results pages
- removes `handleFirstResultFocus` on browse results page. This should only be focused when user selects filters, which still works
> [Our415-Bug-42] Fix scroll issue

- app/components/ui/Navigation/Navigation.module.scss
🎫: [Update Our415 Logo](https://www.notion.so/exygy/Update-Our415-Logo-18a3433f03d08081b7c0c92f3065328d?pvs=24)
This PR:
- adds new header logo to strapi
- adds new footer logo to project (this is the way it was before, we can create a ticket to add this to strapi if we want)
- updates css to make these logos look good within our existing components (they are different aspect ratio from former logo, used my own discretion on this)
HEADER:
| desktop |    <img width="350" alt="image" src="https://github.com/user-attachments/assets/3ef7b411-71d6-4e5e-9c74-770187f09143" />   | <img width="350" alt="image" src="https://github.com/user-attachments/assets/afe36436-c78f-4bc4-bfc2-76c62970d191" />|
| mobile  |   Didn't take screenshot     | …
> above tablet should be same height navbar as desktop

- app/components/SearchAndBrowse/Sidebar/Sidebar.module.scss
add on to #311 
Adds `position: sticky` back to .sidebar only on full width screen. Was causing issues where the sidebar was still 100vh but scrolled upward to leave white space at the bottom of the section
Before:
After:
> [Our415-Bug-57-fix] Fix issue introduced by 

- app/components/DetailPage/MapOfLocations.tsx
- app/components/SearchAndBrowse/SearchMap/SearchMap.tsx
- app/utils/map.test.ts
- app/utils/map.ts
🎫: [Map marker issues](https://www.notion.so/exygy/Map-marker-issues-1973433f03d080d3b39cf118bc077701?pvs=24)
Fixes the issues of multiple services at the same location's markers being stacked on top of each other
Changes:
- Adds an algorithm to create a grid layout of the markers, where the epicenter is the service's location
- reverses the order of markers so that, before if there were 10 markers (1-10) at the same location, the user would see 10 on top, now they see 1 on top
NOTE: Unfortunately I had to recreate the same logic with slight variations for both SearchMap and MapOfLocations. They're different enough that shared helpers won't work without some significant refactoring, which is not a priority ahead of Feb 22 
| zoomed …
> [Our415-T-148] Map marker issues

- app/components/EmailSignup/Emailsignup.tsx
🎫: [Wrong link to the sign up survey](https://www.notion.so/exygy/Wrong-link-to-the-sign-up-survey-1823433f03d0806d92a7c0bd97681595?pvs=4)
This PR:
- Adds new signup form link
- Makes the popup window a little longer to accommodate all fields / buttons
| desktop |   <img width="350" alt="image" src="https://github.com/user-attachments/assets/7e877884-f426-4a04-a6c3-493e7e892e8e" /> |    <img width="350" alt="Screenshot 2025-02-17 at 11 26 27 AM" src="https://github.com/user-attachments/assets/ea364309-9d0d-4e52-92c8-059cdf680aa4" />|
> [OUR415-BUG-35] sign up link change

- app/components/ui/Navigation/MobileNavigation.module.scss
> Remove gap between navbar and navigation on tablet sized screens

- app/components/ui/inline/Button/Button.tsx
- app/pages/HomePage/HomePage.tsx
Per Kyle and Nick's request.
Adds ids to the Browse Services and Featured Events sections so the Homepage CTA can link to them
> add anchor ids to services and events sections on homepage

- .github/workflows/deploy-production.yml
This PR removes the deploy github actions to see if we can rely on the connection set in heroku instead. Hoping this will fix our broken auto-deploy.
> Rm heroku deploy gh actions

- app/hooks/StrapiAPI.ts
- app/pages/EventDetailPage/EventDetailPage.tsx
| desktop |        |       |
| mobile  |        |       |
> pull EventDetailPage dev changes to prod

- app/hooks/StrapiAPI.ts
I think we don't need our admin API token as our Bearer JWT token. Testing this on staging.
> Strapi Fix - Remove Bearer token
