Exygy/askdarcel-web

Procfile, static.json
**Description**
This file adds two files necessary for Heroku deployments, the Procfile and a static.json file.
**Tasks**
- add Procfile that points to the nginx conf file
- add static json file indicating where build location is
=> add Procfile and static.json files

.github/workflows/deploy-development.yml, Dockerfile, docker/templates/default.conf.template, webpack.config.js
- update webpack environments to be 1:1 with config.yml files for environment var usage
- update nginx default conf template to use environment var for host header
- update dockerfile to work with heroku
=> Exygy docker nginx update

.github/workflows/deploy-development.yml
=> add remaining env vars

.github/workflows/build_and_test.yml
=> change title to build and test; add lint job

Procfile, static.json
=> remove heroku files we no longer need

README.md
=> update read me for contribution info

README.md
=> update readme to include env vars

README.md
=> improve sentence

README.md
=> Update readme 06 04 24

.github/workflows/deploy-development.yml
=> add env vars to deploy workflow

app/components/ui/Hero/Hero.module.scss, app/components/ui/Hero/Hero.tsx, app/components/ui/inline/Button/Button.module.scss, app/components/ui/inline/Button/Button.tsx, app/pages/HomePage/HomePage.tsx, app/styles/main.scss, app/styles/st-base/_forms.scss, app/styles/utils/_borders.scss, app/styles/utils/_colors.scss
This PR addresses[ #120](https://www.notion.so/exygy/Global-Button-Link-Styling-9fd96164d17540fd9e6c33d16f32a408)
Adds a button with all four variants (primary, secondary, linkBlue, linkWhite) and options to add left or right arrows. Each button can be an internal link, external link or onClick button. Buttons default to full width on mobile but there is a prop to disable that.
Visit the homepage and there is a temporary section so you can see all buttons in action. You can see all variants, and some with internal links, external links and onClicks as well as arrows. On approval, I will delete that section from the homepage.
- Read and understand …
=> Button styles

docker/templates/default.conf.template
change dns resolver to use google's instead of local
deploy and cross your fingers
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are small remaining changes but the PR is otherwise good to go
If you have one commit and message, squash. If you need each message to be applied, rebase and merge.
=> update resolver dns ip

docker/templates/default.conf.template
update proxy pass url to use v2 in url
merge and cross fingers
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are small remaining changes but the PR is otherwise good to go
If you have one commit and message, squash. If you need each …
=> add v2 to proxy pass for v2 routes

docker/templates/default.conf.template
this makes the proxy pass in the nginx config by omitting the /api/ substring
merge and cross fingers
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are small remaining changes but the PR is otherwise good to go
If you have one commit and …
=> update v2 proxy pass 1:1 to v1 (omit /api/)

.gitignore
I do some things in vscode that write to these files. This is a standard starter pack of ignores until devs using vscode decide on sharing settings which we can do by uncommenting commented lines.
=> Adds vscode gitignore directives

app/components/ui/Section/CategorySection.tsx, app/components/ui/Section/OppEventCardSection.tsx, app/pages/AboutPageOur415/AboutPage.tsx, app/pages/HomePage/HomePage.tsx
This PR addresses [Loading state](https://www.notion.so/exygy/Loading-state-ab8b77bb8b234e18ba97b6992897cd34)
Quick PR! The ticket called for a Loader state, but there was already one that fit designs in the project. This PR just swaps out any "Loading..." message with the <Loader /> component. 
Visit homepage or a service page and notice the loader.
- Either explicitly ask a clarifying question, request changes, or approve the …
=> Loader component

app/components/ui/Cards/CategoryCard.tsx, app/components/ui/Section/CategorySection.tsx, app/components/ui/Section/OppEventCardSection.tsx, app/models/Meta.ts, app/pages/HomePage/HomePage.tsx, app/pages/HomePage/components/Section/Section.tsx
This PR addresses [Hardcode Category Cards on Homepage](https://www.notion.so/exygy/Hardcode-Category-Cards-on-Homepage-09a3b131e6ba4a449272983f33b1da3f)
This PR swaps out the sanity data with hardcoded category cards on the homepage, so that we can have working links on the homepage for MVP. Not only are we switching from sanity, the proposed top level categories are not available to us yet.
Visit homepage, check the category cards section against the mockups, click through and a11y test.
- Also review the acceptance criteria on the Netlify deploy preview (noting …
=> Hardcoded categories on homepage

app/components/search/Header/Header.tsx, app/components/search/SearchAndServiceResultsPage.module.scss, app/components/search/SearchMap/SearchMap.scss, app/components/search/SearchMap/SearchMap.tsx, app/components/search/SearchResults/SearchResults.module.scss, app/components/search/Sidebar/Sidebar.module.scss, app/components/ui/Cards/CategoryCard.tsx, app/components/ui/MapElements.tsx, app/components/ui/Section/CategorySection.tsx, app/components/ui/Section/OppEventCardSection.tsx, app/models/Meta.ts, app/pages/HomePage/HomePage.tsx, app/pages/HomePage/components/Section/Section.tsx, app/styles/utils/_layoututils.scss
This PR addresses [#159](https://www.notion.so/exygy/fea42dc92e6349bfb075b7cbdeea60b6?p=5f55535e466e4ed7bfe6cf4df0520600&pm=c)
Styling ticket for the Google Map on the Search listing page. 
Visit http://localhost:8080/search
[Figma Design](https://www.figma.com/design/iDBeNK7SnZXF8wc3pbPTCY/Our415-Site?node-id=2599-5789&t=w8ORgFTszTX71APg-4)
- Either explicitly ask a clarifying question, request changes, or approve the PR if …
=> Listing map

app/components/search/Header/CustomDropdown.module.scss, app/components/search/Header/CustomDropdown.tsx, app/components/search/Header/Header.module.scss, app/components/search/Header/Header.tsx, app/components/search/SearchMap/SearchMap.scss, app/components/search/SearchMap/SearchMap.tsx, app/pages/SearchResultsPage/SearchResultsPage.tsx
Creates category filter dropdown for category service listings and search results pages. A11y and mobile responsive.
Click any category card on homepage, find the filter dropdown at top of page. Also visit /search and search something and confirm that it says "All categories" instead of a specific category. Traverse through using mouse, keyboard, screen reader.
- Also review the acceptance criteria on the Netlify deploy preview (noting that these …
=> Filter dropdown

config.example.yml, webpack.config.js
This PR addresses [this issue](https://www.notion.so/exygy/Our415-c1bee5dc7fad4f3f988b4fce39e065dc?p=58fcafb274114d1ba774e2491ebb6f79&pm=s).
This branch updates the webpack config so that askdarcel-web can use the staging API for local development.
=> Askdarcel Staging API

app/App.tsx, app/components/listing/LabelTagRows.module.scss, app/components/listing/LabelTagRows.tsx, app/components/listing/ListingInfoTable.module.scss, app/components/listing/ListingInfoTable.tsx, app/components/listing/PageWrapper.module.scss, app/components/search/SearchResults/SearchResults.module.scss, app/components/search/SearchResults/SearchResults.tsx, app/components/ui/LabelTag.module.scss, app/components/ui/LabelTag.tsx, app/pages/OrganizationListingPage.tsx, app/pages/ServiceListingPage/ServiceListingPage.tsx
This PR addresses [Add Tags to Single Page](https://www.notion.so/exygy/Add-Tags-to-Single-Page-b611cc38b6b14fe2a9fb5396b09ac776)
This PR adds top level, subcategory and eligiblity tags to the single service page. It also introduces a LabelTag component and swaps out old labels with this component. Also adds some style improvements for responsiveness to the search results and single listing page.
Visit any single service page and notice the "Tags" section (only displays if there if listing has categories or eligibilities) …
=> Listing page tags

app/Router.tsx, app/components/ui/Accordions/Accordion.module.scss, app/components/ui/Accordions/Accordion.tsx, app/components/ui/TwoColumnContentSection/TwoColumnContentSection.module.scss, app/components/ui/TwoColumnContentSection/TwoColumnContentSection.tsx, app/hooks/StrapiAPI.ts, app/pages/FaqPage/FaqPage.tsx
=> Faq accordion

app/components/search/Sidebar/MapToggleButtons.tsx, app/components/ui/Cards/CategoryCard.module.scss, app/components/ui/Cards/OppEventCard.module.scss, app/components/ui/MapElements.tsx, app/styles/st-base/_layout.scss
Handles focus color change per: https://www.notion.so/exygy/Focus-outline-dfee6a3c159244028c9769209bed011c
=> Change focus color to black for a11y

app/components/ui/Section/OppEventCardSection.tsx
Adds optional lookups so a missing image won't brick the entire page.
=> [241] Fixes handling of missing image data

app/components/search/SearchResults/SearchResult.tsx, app/components/search/SearchResults/SearchResults.tsx
I'm not religiously dogmatic about `single component per file` but in this case there's a lot of colliding terminology and props that even only at 300 lines of code I'm finding it challenging to move around this file. 
This is a simple extraction, no change in behavior.
=> Extracts `SearchResult` component from `SearchResults`

app/components/ui/Cards/FormattedDate.tsx, app/components/ui/Cards/OppEventCard.tsx, app/hooks/StrapiAPI.ts
This fixes up the frontend now that the backend has been deployed.
=> [OUR415-178] Updates homepage query to fetch `calendar_event` and fixes date/time rendering

.github/dependabot.yml
Yellow squad has agreed to give dependabot a try, including experimental version updates: https://exygy.slack.com/archives/C06T4125086/p1723478403965399
Per github recommendations: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates#example-dependabotyml-file
=> Adds dependabot config file for opening PRs for version updates

app/components/ui/TwoColumnContentSection/TwoColumnContentSection.module.scss
Closes `[Two Column Content Section] (with left aligned media) has strange margin-left on some breakpoints` todo of Visual bugs multi ticket.
Removes space on left of two column content section at tablet ish sized breakpoint
=> Two column container minor visual bug

.github/workflows/deploy-production.yml
🙊 Oops.
🎟️ : https://www.notion.so/exygy/Fix-prod-build-1efdfb9b25f34cc1ac2a35cd221596b1?pvs=4
=> Adds Strapi keys to production workflow

app/models/Service.test.ts, app/models/Service.ts, app/pages/ServiceListingPage/ServiceListingPage.tsx, app/utils/DataService.ts
- Builds on additions in https://github.com/Exygy/askdarcel-web/pull/170. 
- Creates a structured error object with `message` and `error` properties
- This is an incremental improvement upon passing unstructured strings around, let's see how this plays out as we begin to test in prod 
---
🎫 https://www.notion.so/exygy/Add-error-handling-for-missing-service-5e0dfc2f5f6d44c1abf6c841be36ebdd?pvs=4
=> [Our415-242] Improves fetch error reporting and Service fetching error handling

app/pages/HomePage/HomePage.tsx, package-lock.json, package.json, webpack.config.js
See code comment for explanation. 
---
🎫 https://www.notion.so/exygy/Undefined-process-webpack-not-setting-correctly-edce170ee0974c37ba3f45f3425dbc0a?pvs=4
=> [OUR415-272] Fixes undefined process being written into third-party deps

docker/templates/default.conf.template
Adds additional configs and file types as recommended by https://www.digitalocean.com/community/tutorials/how-to-improve-website-performance-using-gzip-and-nginx-on-ubuntu-20-04
Who knows, someday someone with better nginx chops may be come along and blow our minds with something different.
=> Updates gzip configs

.eslintrc.js, app/components/listing/ListingInfoTable.tsx, app/components/search/Refinements/OpenNowFilter.tsx, app/components/search/Sidebar/Sidebar.tsx, app/components/ui/SiteSearchInput.tsx
Turns out I was missing the other side of the condition that sets the checkbox state. Oops!
=> [OUR415-276] Fixes OpenNow checkbox display

docker/templates/default.conf.template, webpack.config.js
This shaves off another ~100kb to the final payload.
```
1.7M Sep 10 19:06 bundle.js
404K Sep 11 12:31 bundle.js.gz
326K Sep 11 12:23 bundle.js.br
```
=> Adds brotli compression with gzip fallback

app/components/search/Refinements/ClearSearchButton.tsx
Before:
https://github.com/user-attachments/assets/75853c68-d57f-468f-8b3e-dc7f987ef163
After: 
https://github.com/user-attachments/assets/0ff13810-3273-4749-9681-91eaa68153ed
=> [OUR415-288] Fixes clearing search query

app/components/search/Header/SearchHeaderSection.tsx, app/components/search/SearchResults/SearchResults.tsx
🎫 : https://www.notion.so/exygy/Update-Search-Results-UI-801cab4a270e48439518bc513b324586?pvs=4
=> Updates display of query and results on Search result pages

app/components/search/Header/BrowseHeaderSection.tsx, app/components/search/Header/CustomDropdown.tsx, app/components/search/Header/Header.module.scss, app/components/search/Header/Header.tsx, app/components/search/Header/SearchHeaderSection.tsx, app/components/search/SearchAndServiceResultsPage.module.scss, app/pages/SearchResultsPage/SearchResultsPage.tsx, app/pages/ServiceDiscoveryResults/ServiceDiscoveryResults.tsx
🎟️ : [Incorrect label on service browsing area secondary header](https://www.notion.so/exygy/Incorrect-label-on-service-browsing-area-secondary-header-1113433f03d08015989bd372bfea9b69?pvs=4)
🎟️ : [Search results secondary header UI](https://www.notion.so/exygy/Search-results-secondary-header-UI-1113433f03d0807ea8cbcd06c218284d?pvs=4)
=> [OUR415-297] [OUR415-298] Updates secondary headers for Browse and Search pages

app/App.tsx, app/components/EmailSignup/Emailsignup.tsx, app/components/search/SearchResults/SearchResult.tsx, app/components/ui/SiteSearchInput.tsx, app/hooks/StrapiAPI.ts, app/pages/SearchResultsPage/SearchResultsPage.tsx, test/helpers/createSearchClient.ts
🎫: [Resolve all lint warnings](https://www.notion.so/exygy/Resolve-all-lint-warnings-1373433f03d080e28445effd9e51f746?pvs=24)
This resolves all current lint warnings. Adds a couple lint disable lines.
I tried writing types for createSearchClient requests but it added unnecessary complexity so I disable the warning on that line
=> [Our415-317] Resolve all lint warnings

app/components/ui/Footer/Footer.tsx, app/pages/AboutPage/AboutPage.tsx, app/pages/FaqPage/FaqPage.tsx
🎟️ : [Make sure the sign up component is on every page of Our415](https://www.notion.so/exygy/Make-sure-the-sign-up-component-is-on-every-page-of-Our415-1493433f03d080bdad82f4eef3356907?pvs=4)
=> [OUR415-95] Adds Subscribe Form to global footer

heroku.yml
This branch adds a heroku config file for deploying via a Docker container.
=> adds heroku config file

heroku.yml
This updates the web command for heroku.
=> updates heroku config web command

heroku.yml
Further debugging deployment. Updating heroku config.
=> removes the web run command from heroku config

app/components/EmailSignup/Emailsignup.tsx, app/components/SearchAndBrowse/Header/BrowseSubheader.tsx, app/components/SearchAndBrowse/Pagination/ResultsPagination.tsx, app/components/SearchAndBrowse/Refinements/ClearSearchButton.tsx, app/components/SearchAndBrowse/SearchMap/SearchMap.tsx, app/components/SearchAndBrowse/SearchResults/SearchResults.module.scss, app/components/SearchAndBrowse/Sidebar/Sidebar.tsx, app/components/ui/Navigation/Navigation.tsx, app/components/ui/Navigation/PageHeader.tsx, app/components/ui/Navigation/TopBanner.tsx, app/components/ui/SiteSearchInput.tsx
🎫: [Print view needs some elements hidden](https://www.notion.so/exygy/Print-view-needs-some-elements-hidden-1823433f03d0805cafb4d04dc3f0bb5c?pvs=4)
This PR fixes the print view screen on browse and search results pages by hiding elements w/ CSS that don't need to be on the print view
=> [Our415-BUG-39] Hide elements in print view

Dockerfile
=> undo dockerfix

app/components/SearchAndBrowse/Sidebar/Sidebar.tsx
Add 'Full map area' radio button to distance filter. This radio is selected on page load because value = "all". 
User must be located in SF to see this.
=> [OUR415-T-156] Add 'Full map area' radio button to distance filter

app/Router.tsx
Routes for two urgent events before we make these dynamic.
=> routes for two urgent events

.github/workflows/deploy-production.yml
Reverts Exygy/askdarcel-web#342
=> Revert "Remove heroku deploy github actions"

.github/workflows/deploy-production.yml
| desktop |        |       |
| mobile  |        |       |
=> add install step before heroku deploy in gh actions

app/hooks/StrapiAPI.ts
After testing one API call without a Bearer token, I'm moving forward with removing all of them. This should make it so 500 errors no longer happen.
=> Strapi fix 6/26 
